export const GET_CLIENTS = 'GET_CLIENTS';
export const NEW_CLIENT = 'NEW_CLIENT';
export const ERROR_NEW_CLIENT = 'ERROR_NEW_CLIENT';
export const CLEAN_CLIENTS = 'CLEAN_CLIENTS';

export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const ERRPR_UPDATE_CLIENT = 'ERRPR_UPDATE_CLIENT';

export const SEARCH_CLIENT = 'SEARCH_CLIENT';

export const REFRESCH_CLIENTS = 'REFRESCH_CLIENTS';